---
- name: Install JFrog Artifactory and Xray
  hosts: all
  become: true

  vars:
    artifactory_version: "7.23.15"
    xray_version: "3.23.1"

  tasks:
    - name: Install Java
      package:
        name: java-1.8.0-openjdk
        state: present

    - name: Download Artifactory
      get_url:
        url: "https://releases.jfrog.io/artifactory/artifactory-pro-rpms/artifactory-pro-{{ artifactory_version }}.rpm"
        dest: /tmp/artifactory.rpm

    - name: Install Artifactory
      package:
        name: /tmp/artifactory.rpm
        state: present

    - name: Download Xray
      get_url:
        url: "https://releases.jfrog.io/xray-generic-local/jfrog-xray-{{ xray_version }}.zip"
        dest: /tmp/xray.zip

    - name: Unzip Xray
      unarchive:
        src: /tmp/xray.zip
        dest: /opt/
        remote_src: true
        extra_opts: [--strip-components=1]

    - name: Start Artifactory and Xray services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - artifactory
        - xray
