---
- hosts: postgres_servers
  collections:
    - community.postgresql
    - community.general
    - jfrog.platform
  roles:
    - role: postgres
      when: postgres_enabled | bool

- hosts: xray_servers
  collections:
    - community.general
    - jfrog.platform
  roles:
    - role: xray
      when: xray_enabled | bool
